### PR TITLE
fix(landing): web responsiveness

### PR DESCRIPTION
**Pull request by ArnavK-09**
Ah, here we go again!
It's last try, if it doesn't pass I'll quit!

Sorry for 4 pathetic prs

## Fixed Responsiveness for:-

- [x] Footer Links 
- [x] Feature's Cards
- [x] Pricing Table

### CODE REVIEW

**Comment by ArnavK-09** [comment]
Real hell, bye, sorry for distributing

**Comment by ixartz** [comment]
You should not be able to push without a correct commit message, I suppose you are pushing with `no-verify`, you should have a local feedback before the CI.

**Comment by ArnavK-09** [comment]
> You should not be able to push without a correct commit message, I suppose you are pushing with `no-verify`, you should have a local feedback before the CI.

I'm editing directly from GitHub website since it's a little change yet powerful!

It's just whitespace that got me :(

**Comment by ixartz** [comment]
FYI, the SaaS Boilerplate is now fully responsive

**Comment by ArnavK-09** [comment]
> FYI, the SaaS Boilerplate is now fully responsive 🎉
> 
> You can find the PR at: https://github.com/ixartz/SaaS-Boilerplate/pull/13

Congo 🎉

**Pull request closed without merging**
