### PR TITLE
fix(landing): responsiveness

### PR DESCRIPTION
**Pull request by ArnavK-09**
## Fixed Responsiveness for:-

- [x] Footer Links 
- [x] Feature's Cards
- [x] Pricing Table

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@ixartz sorry, but can you run ci

**Comment by ArnavK-09** [comment]
F

**Comment by ArnavK-09** [comment]
So the ci doesn't tell me problem in one time, it's new problem to use lower case f.
To fix it I need new pr, isn't it would be spam?

Squashing this pr with right title would pass the ci on main repo (last opt)

**Comment by ixartz** [comment]
Merging/Squashing with a failing test is not an option.

Lint-staged/commitlint should prevent you to push your code. Please don't bypass lint-staged/commitlint.

**Pull request closed without merging**
