### PR TITLE
patch(landing): UI tweaks for responsiveness

### PR DESCRIPTION
**Pull request by ArnavK-09**
## Fixed Responsiveness for:-

- [x] Footer Links 
- [x] Feature's Cards
- [x] Pricing Table

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@ixartz could you squash it? To avoid commit messages

**Comment by ixartz** [comment]
Thank you so much for your PR, but it's preferable to make the change directly, so all the tests can run properly before merging it.

Currently, the linter is not run, also the unit tests, etc.

**Comment by ArnavK-09** [comment]
Moved to #4

**Comment by ArnavK-09** [comment]
Moved to #5

**Pull request closed without merging**
