### PR TITLE
fix(landing): UI tweaks for responsiveness

### PR DESCRIPTION
**Pull request by ArnavK-09**
## Fixed Responsiveness for:-

- [x] Footer Links 
- [x] Feature's Cards
- [x] Pricing Table

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@ixartz could you allow vercel check?

**Comment by ixartz** [comment]
@ArnavK-09, The GitHub Actions is failing, thank you in advance.

**Comment by ArnavK-09** [comment]
> @ArnavK-09, The GitHub Actions is failing, thank you in advance.

So, you can **squash merge** this pr to prevent CI GitHub action fail, it would be alright 

And for vercel, you need to approve the preview request from website or link above!

After squash merging the actions would be successful hopefully

As this pr is important for ux/ui for mobile users, current landing page is awful mobile

**Comment by ArnavK-09** [comment]
> @ArnavK-09, The GitHub Actions is failing, thank you in advance.
@ixartz 

So, you can **squash merge** this pr to prevent CI GitHub action fail, it would be alright 

And for vercel, you need to approve the preview request from website or link above!

After squash merging the actions would be successful hopefully

As this pr is important for ux/ui for mobile users, current landing page is awful mobile

**Comment by ixartz** [comment]
@ArnavK-09 I'm not referring to Vercel, please make sure "CI / Run all tests (20.x) (pull_request)" is passing. The PR will not merge or squash if the PR is not passing. I'm not counting the Vercel one, the rest of 3 GitHub Actions should pass.

**Comment by ArnavK-09** [comment]
Squashing this pr might allow that GitHub ci to pass on main repo

**Comment by ixartz** [comment]
As you see here: https://github.com/ixartz/Next-js-Boilerplate/pull/264, all the tests is passing before I merge/squash the PR.

Yes, please create new PR with conventional commits, thank you in advance.

**Pull request closed without merging**
